// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RcppGenLatticeLag
Rcpp::NumericVector RcppGenLatticeLag(Rcpp::NumericVector vec, Rcpp::List nb, int lagNum);
RcppExport SEXP _infocausality_RcppGenLatticeLag(SEXP vecSEXP, SEXP nbSEXP, SEXP lagNumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< int >::type lagNum(lagNumSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGenLatticeLag(vec, nb, lagNum));
    return rcpp_result_gen;
END_RCPP
}
// RcppGenGridLag
Rcpp::NumericVector RcppGenGridLag(Rcpp::NumericMatrix mat, int lagNum);
RcppExport SEXP _infocausality_RcppGenGridLag(SEXP matSEXP, SEXP lagNumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type lagNum(lagNumSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGenGridLag(mat, lagNum));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_infocausality_RcppGenLatticeLag", (DL_FUNC) &_infocausality_RcppGenLatticeLag, 3},
    {"_infocausality_RcppGenGridLag", (DL_FUNC) &_infocausality_RcppGenGridLag, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_infocausality(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
