# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppGenLatticeLagUni <- function(vec, nb, lagNum = 1L) {
    .Call(`_infocausality_RcppGenLatticeLagUni`, vec, nb, lagNum)
}

RcppGenLatticeLagMulti <- function(vecs, nb, lagNums) {
    .Call(`_infocausality_RcppGenLatticeLagMulti`, vecs, nb, lagNums)
}

RcppGenGridLagUni <- function(mat, lagNum = 1L) {
    .Call(`_infocausality_RcppGenGridLagUni`, mat, lagNum)
}

RcppGenGridLagMulti <- function(mat, nrow, lagNum = 1L) {
    .Call(`_infocausality_RcppGenGridLagMulti`, mat, nrow, lagNum)
}

RcppGenTSLagMulti <- function(mat, lagNum = 1L) {
    .Call(`_infocausality_RcppGenTSLagMulti`, mat, lagNum)
}

